### ISSUE TITLE
Syntax coloring

### ISSUE THREAD

**Issue by svipben** [joshpeng/Sublime-Babel-VSCode#19]
Hello,

In my opinion default VS Code syntax coloring is way better than this one. Better improve some of them which are not in VS Code by default, like colored comments and so on. Because right now VS Code default syntax coloring is easier to read. I was like, cool Babel plugin for VS Code which will improve syntax coloring, but the true is, it does nothing at all. Sorry, but this is true, you can really make this plugin better, but you need to improve it.

Thanks

**Comment by joshpeng** [comment]
Thanks for your thoughts, but it really depends on the tmTheme you are using. In more recent releases, VS Code has significantly altered their own grammar scopes and themes. This plugin was made a long time before that. If you are using the newer default VS Code themes, this grammar may not necessarily respect the new scopes and will end up looking off.

Please also note that this grammar was intended to match Sublime Text's Babel package, for better or worse, and not necessarily for "best correctness". At time of release, it was a near perfect 1:1 port, but since then many changes on VS Code have occurred and I can no longer guarantee 1:1.
