### ISSUE TITLE
Is this based on JavaScript Ultimate?

### ISSUE THREAD

**Issue by kurtextrem** [joshpeng/Sublime-Babel-VSCode#6]
Sublime's default syntax also has quite a few flaws. JavaScript Ultimate for ST3 aims to fix that: https://packagecontrol.io/packages/JavaScript%20Ultimate

So, I wonder if this extension is based on JS Ultimate or if it is a good idea to do that? :)

**Comment by joshpeng** [comment]
Great question. This currently implements a modified version of https://packagecontrol.io/packages/Babel

**Comment by kurtextrem** [comment]
It seems like Sublime Babel is getting a rewrite too: https://github.com/babel/babel-sublime/issues/293.

So I'm not sure. Is there any "convenient" way to convert .sublime-syntax to the VS Code JSON?

**Comment by joshpeng** [comment]
Unfortunately, until its done, I won't be touching it. When it's done, if he achieves his goals, there would be no need for me to do anything since we will be able to just import his .tmLanguage. If he can't migrate off sublime-syntax, then we'll see what we see at that point in time.

No way to switch to JS Ultimate without literally starting everything over. There's no convenient way to do grammar. Many things don't necessarily translate the way you'd hope and sometimes require hefty tweaks. Add on top of that the upcoming VSC 1.9 changes that will already break a majority of VSC themes. The whole situation needs to settle a bit more before reassessing what can/cannot be done. Thanks for the links though.

**Comment by kurtextrem** [comment]
I see, thanks for answering and doing Sublime Babel for VS Code :)
