### ISSUE TITLE
Static keyword highlighting is wrong

### ISSUE THREAD

**Issue by YuziRussianHax** [joshpeng/Sublime-Babel-VSCode#8]
![image](https://cloud.githubusercontent.com/assets/14042959/22626601/1e2b993e-ebba-11e6-8c20-f42307d78e97.png)
There is wierd 'static' keyword highlighting in .jsx react component in ES6 syntax (https://facebook.github.io/react/docs/react-component.html).

Specs: Windows 7 SP 1 (also Ubuntu 16.10), VSCode 1.8.1, 1.9.0.
Tested on a lot of Color Schemes (sublime-babel supported and others).

**Comment by joshpeng** [comment]
Please try the ```static``` [branch](https://github.com/joshpeng/Sublime-Babel-VSCode/commit/f92949b404a39ed38528d9035c17b463451032ff) I just pushed. Let me know if that resolves it for you without introducing any other new issues.

This issue seems to also happen in the original Sublime Text grammar that this is based on.

**Comment by YuziRussianHax** [comment]
@joshpeng Everything works just fine without any other issues, thank you a lot :)
![image](https://cloud.githubusercontent.com/assets/14042959/22644342/d7fed85c-ec6a-11e6-9de1-80660712b462.png)
